[package]
name = "advent-of-code-2023"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.6"
nom = "7.1"
itertools = "0.12"
arrayvec = "0.7"
rustc-hash = "1.1"

[profile.release]
debug = true
